SaladBack/SaladBack/Areas/AdminOfSalads/Controllers/FruitController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SaladBack.Core;
using SaladBack.Data.DAL;
using SaladBack.Service.Extentions;

namespace SaladBack.Areas.AdminOfSalads.Controllers
{
    [Area("AdminOfSalads")]
    public class FruitController : Controller
    {
        private readonly SaladDbContext _context;
        private readonly IWebHostEnvironment _env;

        public FruitController(SaladDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }
        public IActionResult Index()
        {
            List<Fruit> fruits = _context.Fruits.OrderByDescending(p => p.Id).ToList();
            return View(fruits);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Fruit fruit)
        {
            if (_context.Fruits.Any(f => f.Name == fruit.Name))
            {
                ModelState.AddModelError("", "Same Value");
                return View();
            };
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Check Value");
                return View();
            }
            
            //_env.WebRootPath/assets/images
            string imagePath = Path.Combine(_env.WebRootPath, "assets", "images");
            fruit.ImageUrl = fruit.Image.AddImage(imagePath);

            _context.Fruits.Add(fruit);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]

        public IActionResult Edit(int id) {
            Fruit? fruit = _context.Fruits.FirstOrDefault(f => f.Id == id);
            return View(fruit);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int? id, string name, string desc, IFormFile image)
        {
            if (id is null) return BadRequest();
            Fruit? fruit = _context.Fruits.FirstOrDefault(f => f.Id == id);
            if (fruit is null) return BadRequest();

            if (_context.Fruits.Any(f => f.Name == name && f.Id != id)) {
                ModelState.AddModelError("Name", "Same Name");
                return View();
            }
            fruit.Name = name;
            fruit.Desc = desc;
            _context.SaveChanges();
            return RedirectToAction("Index");

        }


        [HttpGet]
        public IActionResult Detail(int? id)
        {
        if(id is null) return NotFound();
        Fruit? fruit = _context.Fruits.SingleOrDefault(f => f.Id == id);
        if (fruit is null) return BadRequest();
        return View(fruit);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id is null) return NotFound();
            Fruit? fruit = _context.Fruits.SingleOrDefault(f => f.Id == id);
            if (fruit is null) return BadRequest();
            return View(fruit);
        }
        [HttpPost]
        public IActionResult Delete(Fruit fruit)
        {

         _context.Fruits.Remove(fruit);
            _context.SaveChanges();
        return RedirectToAction("Index");
        }

        
        public IActionResult Search(string name)
        {
            List<Fruit> fruits = _context.Fruits.Where(f =>f.Name.ToLower().Contains(name.ToLower())).ToList();
            return PartialView("_FruitPartial", fruits.ToList());
        }


    }
}

SaladBack/SaladBack/Areas/AdminOfSalads/Controllers/FruitSaladController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using SaladBack.Core;
using SaladBack.Core.Models;
using SaladBack.Data.DAL;
using SaladBack.Service.Extentions;
using SaladBack.Service.Services.Interfaces;
using SaladBack.ViewModel;

namespace SaladBack.Areas.AdminOfSalads.Controllers
{
    [Area("AdminOfSalads")]
    public class FruitSaladController : Controller
    {
        private readonly SaladDbContext _context;
        private readonly IFruitService _fruitService;
        private readonly IWebHostEnvironment _env;

        public FruitSaladController(SaladDbContext context, IFruitService fruitService, IWebHostEnvironment env)
        {
            _context = context;
            _fruitService = fruitService;
            _env = env;
        }
        public async Task<IActionResult> Index()
        {
            List<FruitSalad> fruitSalads = await _context.FruitSalads.Include(fs => fs.SaladImages).OrderByDescending(f => f.Id).ToListAsync();
            return View(fruitSalads);
        }
        [HttpGet]
        public async Task<IActionResult> Create(FruitSaladVM vm)
        {
            vm.Fruits = await _fruitService.GetAll();
            vm.Sizes = await _context.Sizes.ToListAsync();
            return View(vm);
        }

        [HttpPost]
        [ActionName("Create")]
        public async Task<IActionResult> CreatePost(FruitSaladVM vm)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Please fill all fields");
                vm.Fruits = await _fruitService.GetAll();
                vm.Sizes = await _context.Sizes.ToListAsync();
                return View(vm);
            }
            if (vm.Name is null)
            {
                ModelState.AddModelError("", "Please fill Name fields");
                vm.Fruits = await _fruitService.GetAll();
                vm.Sizes = await _context.Sizes.ToListAsync();
                return View(vm);
            }
            if (vm.Files is null)
            {
                ModelState.AddModelError("", "Please fill Files fields");
                vm.Fruits = await _fruitService.GetAll();
                vm.Sizes = await _context.Sizes.ToListAsync();
                return View(vm);
            }
            if (vm.FruitId is null)
            {
                ModelState.AddModelError("", "Please fill Fruits fields");
                vm.Fruits = await _fruitService.GetAll();
                vm.Sizes = await _context.Sizes.ToListAsync();
                return View(vm);
            }
            //if (vm.ImageIds is null)
            //{
            //    ModelState.AddModelError("", "Please fill Images fields");
            //    vm.Fruits = await _fruitService.GetAll();
            //    vm.Sizes = await _context.Sizes.ToListAsync();
            //    return View(vm);
            //}


            FruitSalad fruitSalad = new FruitSalad
            {
                Name = vm.Name,
                Price = vm.Price,
                Rating = vm.Rating,
                Count = vm.Count,
                FruitSaladFruits = new List<FruitSaladFruit>(),
                SaladImages = new List<SaladImage>(),
                //Sizes= new List<Size>(),
            };
            if (vm.FruitId != null && vm.FruitId.Any())
            {
                foreach (var id in vm.FruitId)
                {
                    fruitSalad.FruitSaladFruits.Add(new FruitSaladFruit
                    {
                        FruitId = id
                    });
                }
            }

            var size = _context.Sizes.FirstOrDefault(s => s.Id == vm.SizeId);
            if (size == null)
            {
                vm.Sizes = _context.Sizes.AsNoTracking().ToList();
                return View(vm);
            }
            fruitSalad.Sizes?.Add(size);

            //if (vm.SizeId != null && vm.SizeId.Any())
            //{
            //    foreach (var id in vm.SizeId)
            //    {
            //        Size relatedSize = new()
            //        {
            //            FruitSaladId = id, 
            //        };
            //        fruitSalad.Sizes.Add(relatedSize);
            //    }
            //}

            if (vm.Files != null && vm.Files.Any())
            {
                string path = Path.Combine(_env.WebRootPath, "assets", "images");

                foreach (var file in vm.Files)
                {
                    file.AddImage(path);

                    SaladImage saladImg = new()
                    {
                        Url = file.AddImage(path),
                    };

                    fruitSalad.SaladImages.Add(saladImg);
                }
            }

            _context.FruitSalads.Add(fruitSalad);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            if (id == 0) return NotFound();
            FruitSalad? fruitSalad = await _context.FruitSalads
                                                .Include(fs => fs.SaladImages)
                                                .Include(fs => fs.FruitSaladFruits).ThenInclude(fs => fs.Fruit)
                                                .FirstOrDefaultAsync(fs => fs.Id == id);
            if (fruitSalad == null) return NotFound();
            FruitSaladVM vm = new()
            {
                Id = fruitSalad.Id,
                Name = fruitSalad.Name,
                Price = fruitSalad.Price,
                Rating = fruitSalad.Rating,
                Count = fruitSalad.Count,
                ImageIds = fruitSalad.SaladImages?.Select(i => i.Id).ToList(),
                Images = fruitSalad.SaladImages?.ToList(),
                FruitId = fruitSalad.FruitSaladFruits?.Select(i => i.FruitId).ToList(),
                //SizeId = fruitSalad.Sizes?.Select(i => i.FruitSaladId).ToList(),
                Fruits = await _fruitService.GetAll(),
                Sizes = await _context.Sizes.ToListAsync(),
            };
            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, FruitSaladVM vm)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Please fill all fields");
                vm.Fruits = await _fruitService.GetAll();
                vm.Sizes = await _context.Sizes.ToListAsync();
                return View(vm);
            }


            FruitSalad? fruitSalad = _context.FruitSalads?.Include(fs => fs.SaladImages)?
                .Include(fs => fs.FruitSaladFruits).ThenInclude(fs => fs.Fruit)
                .FirstOrDefault(fs => fs.Id == id);

            

            if (vm.FruitId != null && vm.FruitId.Any())
            {
                fruitSalad.FruitSaladFruits.Clear();
                foreach (var idF in vm.FruitId)
                {
                    fruitSalad.FruitSaladFruits.Add(new FruitSaladFruit
                    {
                        FruitId = idF
                    });
                }
            }
            vm.Images = fruitSalad.SaladImages.ToList();
            if (vm.Files != null && vm.Files.Any())
            {
                string path = Path.Combine(_env.WebRootPath, "assets", "images");

                foreach (var file in vm.Files)
                {
                    file.AddImage(path);

                    SaladImage saladImg = new()
                    {
                        Url = file.AddImage(path),
                    };

                    fruitSalad.SaladImages.Add(saladImg);
                }
            }


            if (vm.DeletedImageIds != null)
            {
                if (vm.DeletedImageIds.Count == fruitSalad.SaladImages.Count)
                {
                    ModelState.AddModelError("", "Images can not be null");
                    vm.Fruits = await _fruitService.GetAll();
                    vm.Sizes = await _context.Sizes.ToListAsync();
                    return View(vm);
                }
                foreach (var idD in vm.DeletedImageIds)
                {
                    SaladImage? saladImage = await _context.SaladImage.FirstOrDefaultAsync(i => i.Id == idD);
                    if (saladImage != null)
                    {
                        string path = Path.Combine(_env.WebRootPath, "assets", "images", saladImage.Url);
                        if (System.IO.File.Exists(path))
                        {
                            System.IO.File.Delete(path);
                        }
                        _context.SaladImage.Remove(saladImage);
                    }
                }
            }

            fruitSalad.Name = vm.Name;
            fruitSalad.Price = vm.Price;
            fruitSalad.Rating = vm.Rating;
            fruitSalad.Count = vm.Count;
            //if (vm.SizeId != null && vm.SizeId.Any())
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var product = await _context.FruitSalads.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            var imagesFolderPath = Path.Combine(_env.WebRootPath, "assets", "images");

            var imageFileNames = await _context.SaladImage
                .Where(i => i.FruitSaladId == product.Id)
                .Select(i => i.Url)
                .ToListAsync();

            foreach (var imageFileName in imageFileNames)
            {
                var imagePath = Path.Combine(imagesFolderPath, imageFileName);

                await FileUpload.DeleteImage(imagePath);
            }

            _context.FruitSalads.Remove(product);
            await _context.SaveChangesAsync();

SaladBack/SaladBack/Areas/AdminOfSalads/Views/Shared/_FruitPartial.cshtml
@using SaladBack.Core
@model List<Fruit>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Desc)
        </td>
        <td>
             <img style="width:80px" src="~/assets/images/@item.ImageUrl" alt="@item.Name"/>   
        </td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
            <a asp-action="Detail" asp-route-id="@item.Id">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
        </td>
    </tr>
}

SaladBack/SaladBack/Areas/AdminOfSalads/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>Kaiadmin - Bootstrap 5 Admin Dashboard</title>
    <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no"
          name="viewport" />
    <link rel="icon"
          href="~/admin/assets/img/kaiadmin/favicon.ico"
          type="image/x-icon" />
    <!-- Fonts and icons -->
    <script src="~/admin/assets/js/plugin/webfont/webfont.min.js"></script>
@*     <script>
        WebFont.load({
          google: { families: ["Public Sans:300,400,500,600,700"] },
          custom: {
            families: [
              "Font Awesome 5 Solid",
              "Font Awesome 5 Regular",
              "Font Awesome 5 Brands",
              "simple-line-icons",
            ],
            urls: ["~/admin/assets/css/fonts.min.css"],
          },
          active: function () {
            sessionStorage.fonts = true;
          },
        });
    </script> *@

    <!-- CSS Files -->
    <link rel="stylesheet" href="~/admin/assets/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/admin/assets/css/plugins.min.css" />
    <link rel="stylesheet" href="~/admin/assets/css/kaiadmin.min.css" />

    <!-- CSS Just for demo purpose, don't include it in your project -->
    <link rel="stylesheet" href="~/admin/assets/css/demo.css" />
    <style>
        body {
            background-color: #1a2036;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar -->
        <div class="sidebar" data-background-color="dark">
            <div class="sidebar-logo">
                <!-- Logo Header -->
                <div class="logo-header" data-background-color="dark">
                    <a href="index.html" class="logo">
                        <img src="~/admin/assets/img/kaiadmin/logo_light.svg"
                             alt="navbar brand"
                             class="navbar-brand"
                             height="20" />
                    </a>
                    <div class="nav-toggle">
                        <button class="btn btn-toggle toggle-sidebar">
                            <i class="gg-menu-right"></i>
                        </button>
                        <button class="btn btn-toggle sidenav-toggler">
                            <i class="gg-menu-left"></i>
                        </button>
                    </div>
                    <button class="topbar-toggler more">
                        <i class="gg-more-vertical-alt"></i>
                    </button>
                </div>
                <!-- End Logo Header -->
            </div>
            <div class="sidebar-wrapper scrollbar scrollbar-inner">
                <div class="sidebar-content">
                    <ul class="nav nav-secondary">
                        <li class="nav-item active">
                            <a data-bs-toggle="collapse"
                               href="#dashboard"
                               class="collapsed"
                               aria-expanded="false">
                                <i class="fas fa-home"></i>
                                <p>Dashboard</p>
                                <span class="caret"></span>
                            </a>
                            <div class="collapse" id="dashboard">
                                <ul class="nav nav-collapse">
                                    <li>
                                        <a href="../demo1/index.html">
                                            <span class="sub-item">Dashboard 1</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li>
                        <li class="nav-section">
                            <span class="sidebar-mini-icon">
                                <i class="fa fa-ellipsis-h"></i>
                            </span>
                            <h4 class="text-section">Components</h4>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Fruit" asp-action="Index">
                            Fruit List
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="FruitSalad" asp-action="Index">
                                FruitSalad List
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="main-panel p-3">
        @RenderBody()
        </div>

             @*   <script src="~/admin/assets/js/core/jquery-3.7.1.min.js"></script>
        <script src="~/admin/assets/js/core/popper.min.js"></script>
        <script src="~/admin/assets/js/core/bootstrap.min.js"></script>

        <!-- jQuery Scrollbar -->
        <script src="~/admin/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js"></script>

        <!-- Chart JS -->
        <script src="~/admin/assets/js/plugin/chart.js/chart.min.js"></script>

        <!-- jQuery Sparkline -->
        <script src="~/admin/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js"></script>

        <!-- Chart Circle -->
        <script src="~/admin/assets/js/plugin/chart-circle/circles.min.js"></script>

        <!-- Datatables -->
        <script src="~/admin/assets/js/plugin/datatables/datatables.min.js"></script>

        <!-- Bootstrap Notify -->
        <script src="~/admin/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js"></script>

        <!-- jQuery Vector Maps -->
        <script src="~/admin/assets/js/plugin/jsvectormap/jsvectormap.min.js"></script>
        <script src="~/admin/assets/js/plugin/jsvectormap/world.js"></script>

        <!-- Sweet Alert -->
        <script src="~/admin/assets/js/plugin/sweetalert/sweetalert.min.js"></script>

        <!-- Kaiadmin JS -->
        <script src="~/admin/assets/js/kaiadmin.min.js"></script>

        <!-- Kaiadmin DEMO methods, don't include it in your project! -->
        <script src="~/admin/assets/js/setting-demo.js"></script>
        <script src="~/admin/assets/js/demo.js"></script> *@
       @*  <script>
            $("#lineChart").sparkline([102, 109, 120, 99, 110, 105, 115], {
              type: "line",
              height: "70",
              width: "100%",
              lineWidth: "2",
              lineColor: "#177dff",
              fillColor: "rgba(23, 125, 255, 0.14)",
            });

            $("#lineChart2").sparkline([99, 125, 122, 105, 110, 124, 115], {
              type: "line",
              height: "70",
              width: "100%",
              lineWidth: "2",
              lineColor: "#f3545d",
              fillColor: "rgba(243, 84, 93, .14)",
            });

            $("#lineChart3").sparkline([105, 103, 123, 100, 95, 105, 115], {
              type: "line",
              height: "70",
              width: "100%",
              lineWidth: "2",
              lineColor: "#ffa534",
              fillColor: "rgba(255, 165, 52, .14)",
            });
        </script> *@
</body>
</html>